"use strict";
exports.__esModule = true;
var express_1 = require("express");
var morgan_1 = require("morgan");
var cors_1 = require("cors");
require("dotenv/config");
var helmet_1 = require("helmet");
var mongoose_1 = require("./db/mongoose");
var index_1 = require("./routes/index");
var error_middleware_1 = require("./middleware/error.middleware");
var not_found_middleware_1 = require("./middleware/not-found.middleware");
var app = (0, express_1["default"])();
app.use(express_1["default"].json());
app.use((0, cors_1["default"])());
app.use((0, helmet_1["default"])());
app.use((0, morgan_1["default"])("combined"));
app.use("/api", index_1["default"]);
app.use(error_middleware_1.errorHandler);
app.use(not_found_middleware_1.notFoundHandler);
// const port = config.get<number>("port");
var port = (Number(process.env.PORT) || 3000);
app.get("/", function (req, res) {
    res.send("Hello!");
});
(0, mongoose_1["default"])();
console.log("ffggdfg");
app.listen(port, "0.0.0.0", function () {
    console.log("Server is up on the ".concat(port, " "));
});
console.log("第二航");
