"use strict";
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
exports.__esModule = true;
exports.UpdateReviewInterface = exports.DeleteReviewInterface = exports.CreateReviewInterface = exports.UserPasswordModifyInterface = exports.UserInfoModifyInterface = exports.UploadAvatarInterface = exports.UpdateQtyInterface = exports.UpdateOrderInterface = exports.ResetPasswordInterface = exports.RemoveFromFavInterface = exports.RemoveItemFromCartInterface = exports.RegisterInterface = exports.ModifyProductInterface = exports.RedeemCouponInterface = exports.ModifyCouponInterface = exports.GoogleLoginInterface = exports.GetRefreshTokenInterface = exports.GetProductDetailInterface = exports.GetOrderDetailInterface = exports.ForgotPasswordInterface = exports.DeleteProductInterface = exports.DeleteMultipleProductsInterface = exports.DeleteMultipleCouponsInterface = exports.DeleteCouponInterface = exports.CreateProductInterface = exports.CreateCouponInterface = exports.CreateOrderInterface = exports.ApplyCouponInterface = exports.AddToFavInterface = exports.AddToCartInterface = exports.SendVerifyOrResetLinkInterface = exports.CheckIfTokenIsValidInterface = exports.VerifyUserInterface = exports.CheckIfAccountExistsInterface = exports.LoginInterface = void 0;
var LoginInterface_1 = require("./@Request/LoginInterface");
__createBinding(exports, LoginInterface_1, "default", "LoginInterface");
var CheckIfAccountExistsInterface_1 = require("./@Request/CheckIfAccountExistsInterface");
__createBinding(exports, CheckIfAccountExistsInterface_1, "default", "CheckIfAccountExistsInterface");
var VerifyUserInterface_1 = require("./@Request/VerifyUserInterface");
__createBinding(exports, VerifyUserInterface_1, "default", "VerifyUserInterface");
var CheckIfTokenIsValidInterface_1 = require("./@Request/CheckIfTokenIsValidInterface");
__createBinding(exports, CheckIfTokenIsValidInterface_1, "default", "CheckIfTokenIsValidInterface");
var sendVerifyOrResetLinkInterface_1 = require("./@Request/sendVerifyOrResetLinkInterface");
__createBinding(exports, sendVerifyOrResetLinkInterface_1, "default", "SendVerifyOrResetLinkInterface");
var AddToCartInterface_1 = require("./@Request/AddToCartInterface");
__createBinding(exports, AddToCartInterface_1, "default", "AddToCartInterface");
var AddToFavInterface_1 = require("./@Request/AddToFavInterface");
__createBinding(exports, AddToFavInterface_1, "default", "AddToFavInterface");
var ApplyCouponInterface_1 = require("./@Request/ApplyCouponInterface");
__createBinding(exports, ApplyCouponInterface_1, "default", "ApplyCouponInterface");
var CreateOrderInterface_1 = require("./@Request/CreateOrderInterface");
__createBinding(exports, CreateOrderInterface_1, "default", "CreateOrderInterface");
var CreateCouponInterface_1 = require("./@Request/CreateCouponInterface");
__createBinding(exports, CreateCouponInterface_1, "default", "CreateCouponInterface");
var CreateProductInterface_1 = require("./@Request/CreateProductInterface");
__createBinding(exports, CreateProductInterface_1, "default", "CreateProductInterface");
var DeleteCouponInterface_1 = require("./@Request/DeleteCouponInterface");
__createBinding(exports, DeleteCouponInterface_1, "default", "DeleteCouponInterface");
var DeleteMultipleCouponsInterface_1 = require("./@Request/DeleteMultipleCouponsInterface");
__createBinding(exports, DeleteMultipleCouponsInterface_1, "default", "DeleteMultipleCouponsInterface");
var DeleteMultipleProductsInterface_1 = require("./@Request/DeleteMultipleProductsInterface");
__createBinding(exports, DeleteMultipleProductsInterface_1, "default", "DeleteMultipleProductsInterface");
var DeleteProductInterface_1 = require("./@Request/DeleteProductInterface");
__createBinding(exports, DeleteProductInterface_1, "default", "DeleteProductInterface");
var ForgotPasswordInterface_1 = require("./@Request/ForgotPasswordInterface");
__createBinding(exports, ForgotPasswordInterface_1, "default", "ForgotPasswordInterface");
var GetOrderDetailInterface_1 = require("./@Request/GetOrderDetailInterface");
__createBinding(exports, GetOrderDetailInterface_1, "default", "GetOrderDetailInterface");
var GetProductDetailInterface_1 = require("./@Request/GetProductDetailInterface");
__createBinding(exports, GetProductDetailInterface_1, "default", "GetProductDetailInterface");
var GetRefreshTokenInterface_1 = require("./@Request/GetRefreshTokenInterface");
__createBinding(exports, GetRefreshTokenInterface_1, "default", "GetRefreshTokenInterface");
var GoogleLoginInterface_1 = require("./@Request/GoogleLoginInterface");
__createBinding(exports, GoogleLoginInterface_1, "default", "GoogleLoginInterface");
var ModifyCouponInterface_1 = require("./@Request/ModifyCouponInterface");
__createBinding(exports, ModifyCouponInterface_1, "default", "ModifyCouponInterface");
var RedeemCouponInterface_1 = require("./@Request/RedeemCouponInterface");
__createBinding(exports, RedeemCouponInterface_1, "default", "RedeemCouponInterface");
var ModifyProductInterface_1 = require("./@Request/ModifyProductInterface");
__createBinding(exports, ModifyProductInterface_1, "default", "ModifyProductInterface");
var RegisterInterface_1 = require("./@Request/RegisterInterface");
__createBinding(exports, RegisterInterface_1, "default", "RegisterInterface");
var RemoveItemFromCartInterface_1 = require("./@Request/RemoveItemFromCartInterface");
__createBinding(exports, RemoveItemFromCartInterface_1, "default", "RemoveItemFromCartInterface");
var RemoveFromFavInterface_1 = require("./@Request/RemoveFromFavInterface");
__createBinding(exports, RemoveFromFavInterface_1, "default", "RemoveFromFavInterface");
var ResetPasswordInterface_1 = require("./@Request/ResetPasswordInterface");
__createBinding(exports, ResetPasswordInterface_1, "default", "ResetPasswordInterface");
var UpdateOrderInterface_1 = require("./@Request/UpdateOrderInterface");
__createBinding(exports, UpdateOrderInterface_1, "default", "UpdateOrderInterface");
var UpdateQtyInterface_1 = require("./@Request/UpdateQtyInterface");
__createBinding(exports, UpdateQtyInterface_1, "default", "UpdateQtyInterface");
var UploadAvatarInterface_1 = require("./@Request/UploadAvatarInterface");
__createBinding(exports, UploadAvatarInterface_1, "default", "UploadAvatarInterface");
var UserInfoModifyInterface_1 = require("./@Request/UserInfoModifyInterface");
__createBinding(exports, UserInfoModifyInterface_1, "default", "UserInfoModifyInterface");
var UserPasswordModifyInterface_1 = require("./@Request/UserPasswordModifyInterface");
__createBinding(exports, UserPasswordModifyInterface_1, "default", "UserPasswordModifyInterface");
var CreateReviewInterface_1 = require("./@Request/CreateReviewInterface");
__createBinding(exports, CreateReviewInterface_1, "default", "CreateReviewInterface");
var DeleteReviewInterface_1 = require("./@Request/DeleteReviewInterface");
__createBinding(exports, DeleteReviewInterface_1, "default", "DeleteReviewInterface");
var UpdateReviewInterface_1 = require("./@Request/UpdateReviewInterface");
__createBinding(exports, UpdateReviewInterface_1, "default", "UpdateReviewInterface");
